services:
  go-api:
    container_name: spleet-api
    build: .
    ports:
      - "8080:8080"
    networks:
      - spleet-network
  mysql-db:
    container_name: spleet-api-db
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - spleet-network

networks:
  spleet-network:
    driver: bridge